### ISSUE TITLE
Confusion about the impact of the LLM Models

### ISSUE THREAD

**Issue by YilinGao-SHU** [opendilab/LMDrive#1]
Thanks for your excellent work. I would like to ask if you have compared the results of replacing LLM with Traditional Transformer for end-to-end training? Because judging from the current closed-loop results of Town5, the models introducing LLM do not seem to surpass traditional models, such as interFuser, etc. Where are the performance gains brought by LLM mainly reflected?

**Comment by deepcs233** [comment]
Hi!
The results are obtained on the LangAuto benchmark which only provides the agent with the natural language instructions. The model needs to understand natural language and make decisions. Interfuser, TCP, etc. take as input the clear and explicit target waypoints. The direct comparison between LMDrive and traditional methods is not fair.

**Comment by YilinGao-SHU** [comment]
Thanks for you reply :+1: )

**Comment by YilinGao-SHU** [comment]
Another little question, I wonder if you have any plans to upload the data set to other cloud platforms. For some reasons, it is not easy to download directly from Hugging Face. : (

**Comment by deepcs233** [comment]
Hi!
We are uploading our dataset to the https://opendatalab.org.cn/ , it may take several days due to its large size. I will notice you when it's ready.

**Comment by YilinGao-SHU** [comment]
> Hi! We are uploading our dataset to the https://opendatalab.org.cn/ , it may take several days due to its large size. I will notice you when it's ready.

Thanks again for your reply. : )

**Comment by deepcs233** [comment]
Hi!
We are uploading our dataset to OPENXLAB (by SHLAB): https://openxlab.org.cn/datasets/deepcs233/LMDrive
We've encountered some delays due to slower-than-expected upload speeds. As of now, we have successfully uploaded 15% of the entire dataset. We appreciate your patience as we work towards completing this task.

**Comment by YilinGao-SHU** [comment]
Thanks again for your work！发送自我的盖乐世
-------- 原始信息 --------发件人： Hao Shao ***@***.***> 日期: 2023/12/29  18:48  (GMT+08:00) 收件人： opendilab/LMDrive ***@***.***> 抄送： YilinGao-SHU ***@***.***>, Author ***@***.***> 主题： Re: [opendilab/LMDrive] Confusion about the impact of the LLM Models (Issue #1) 
Hi!
We are uploading our dataset to OPENXLAB (by SHLAB): https://openxlab.org.cn/datasets/deepcs233/LMDrive
We've encountered some delays due to slower-than-expected upload speeds. As of now, we have successfully uploaded 15% of the entire dataset. We appreciate your patience as we work towards completing this task.

**Comment by ryhnhao** [comment]
Hi! @deepcs233 
It seems that we don't have download permission in both two data platform.

https://openxlab.org.cn/datasets/deepcs233/LMDrive/tree/main
https://opendatalab.org.cn/deepcs233/LMDrive/tree/main

Both websites tell: "本站暂不提供直接下载，如需下载请至数据集官网"

Thanks.

**Comment by deepcs233** [comment]
Hi!
Maybe you can try:
https://huggingface.co/datasets/OpenDILabCommunity/LMDrive

**Comment by ryhnhao** [comment]
> Hi! Maybe you can try: https://huggingface.co/datasets/OpenDILabCommunity/LMDrive
> 
> Can you try to log in the openxlab? I tried just now, it's ok.

Hi!
"log in the openxlab" still doesn't work for me:). Maybe you are the contributor so you can download. 
![image](https://github.com/opendilab/LMDrive/assets/153728596/e39492e0-6ba4-4f33-86f2-34b8d34d8c97)
Besides, and opendatalab show the same error.

For some reasons, it is not easy to download directly from Hugging Face (even huggingface mirror). It's too large.

**Comment by deepcs233** [comment]
Hi!
Can you try it again? I set the dataset as private and set it as public again.  And I can download the dataset after I log out. 

BTW, we have only uploaded about 20%+ dataset to the shlab platform.

**Comment by ryhnhao** [comment]
> Hi! Can you try it again? I set the dataset as private and set it as public again. And I can download the dataset after I log out.
> 
> BTW, we have only uploaded about 20%+ dataset to the shlab platform.

Hi!
openxlab works now, whether login in or login out!
Many thanks!

**Comment by ry4nzhu** [comment]
> Hi! The results are obtained on the LangAuto benchmark which only provides the agent with the natural language instructions. The model needs to understand natural language and make decisions. Interfuser, TCP, etc. take as input the clear and explicit target waypoints. The direct comparison between LMDrive and traditional methods is not fair.

I have a follow-up question on this (might be a dumb one as I'm less familiar with the related work): if the previous methods (Interfuser, TCP, etc) take clear and explicit target waypoints as inputs, do the input target waypoints change accordingly as the vehicle drives in the evaluation or is it just a single target (final destination) that the vehicle is supposed to reach?

**Comment by deepcs233** [comment]
Hi!

The previous methods take clear and explicit target waypoints/ discrete commands(turn left, right, etc,) as inputs, and they will be updated according to the status of the AV in real-time.

**Comment by ry4nzhu** [comment]
Thanks a lot for answering. For discrete commands(turn left, right, etc,), are they presented in the form of a target waypoint (so the inputs are consistent)? Otherwise, these previous models have to parse those discrete commands such as left turn and understand them. 

--------------

I know this is a question unrelated to this great code repo, but just out of curiosity, if previous work takes explicit target waypoints/ discrete commands(turn left, right, etc,) can achieve a relatively good driving score (e.g. >70 from ReasonNet), what do you think the strength of leveraging LLM to parse natural language instructions are (as the performance is less good, which make sense because understanding the instruction is hard)? Compared to the traditional models, is it more flexible to interact with human drivers a main strength? Otherwise, taking the traditional methods to use discrete commands and target waypoints already looks like a good solution to me.

**Comment by deepcs233** [comment]
Hi!
It's the first try to apply the LLM in the field of end-to-end autonomous driving. We believe that it's performance will be better and better, until the LLM agent can function as a human driver. Besides, our model can utilize and understand the notice instructions, which can improve the overall safety performance in the long-tail scenarios. In the future, we plan to support more types of instructions, like "I am late, do ignore my comfort and hurry" or "I am feeling sick, please drive slow and careful".
