### ISSUE TITLE
Failed to run carla.

### ISSUE THREAD

**Issue by weimengchuan** [opendilab/LMDrive#10]
Hi, I meet a problem while running carla. Your help would be greatly appreciated.
My command is:
`carla/CarlaUE4.sh --world-port=2000 -opengl`
Error info is:
`Refusing to run with the root privileges.`

**Comment by deepcs233** [comment]
Hi!
It looks like you need to run the Carla with a non-root user.

**Comment by weimengchuan** [comment]
I Fix it! Thanks!
Reason for the previous issue was that our server cluster only supports root privileges.
Now, I success to run carla with a non-root user in an ubuntu PC.

**Comment by CoderXuans** [comment]
> 我解决了！谢谢！ 之前问题的原因是我们的服务器集群仅支持 root 权限。 现在，我成功地在 ubuntu PC 上以非 root 用户身份运行了 carla。

请问在非root用户的/home文件夹下重新下载carla然后启动吗？

**Comment by deepcs233** [comment]
不需要，只需要执行用户不是root就可以
