### ISSUE TITLE
Model principles and running problems in carla

### ISSUE THREAD

**Issue by zhouxiqin2017** [opendilab/LMDrive#11]
@deepcs233 
Hello, thank you for your work. I have two questions for you.
1、This is about the model itself. At that time, when adopting a multimodal large language model, why did llava framework not directly use a linear layer for visual mode and language mode alignment, but Qformer used by blip2 framework for alignment? What other considerations are there?
2、When the model was running in the evaluation part, pygame and multi-modal large model parameters were not loaded, and no error was reported, and the program died directly. The premise has been deployed in accordance with the operation of the model environment, downloaded the weight parameters of the model, began to report errors, after modification has not reported errors, but it is not running.
We look forward to your reply and thank you very much.

**Comment by zhouxiqin2017** [comment]
![lmdrive模型](https://github.com/opendilab/LMDrive/assets/75245944/91a0516a-fe87-4968-8664-d28f0e560922)
This is the interface of model inference.

**Comment by deepcs233** [comment]
Hi!
For your questions:
1. The number of visual tokens from each frame is about 200 and each scenario(navigation instruction) needs about 10-100 frames to complete. We must reduce the token number by using q-former.
2. The default evaluation setting is RESUME=TRUE. It means that the evaluation will skip directly if you have finished it before. There are two ways to solve this problem. (1) set RESUME=False in run_evaluation.sh (2) delete results/sample_result.json (may be other similar file)

**Comment by zhouxiqin2017** [comment]
> Hi! For your questions:
> 
> 1. The number of visual tokens from each frame is about 200 and each scenario(navigation instruction) needs about 10-100 frames to complete. We must reduce the token number by using q-former.
> 2. The default evaluation setting is RESUME=TRUE. It means that the evaluation will skip directly if you have finished it before. There are two ways to solve this problem. (1) set RESUME=False in run_evaluation.sh (2) delete results/sample_result.json (may be other similar file)

Ok, thank you for your patient reply. I will try it here and consult you if I have any questions. Thank you again.

**Comment by zhouxiqin2017** [comment]
@deepcs233 
Hello, I'm sorry to bother you again, but I still have some questions about the model evaluation.
This is my model configuration parameters page.
![image](https://github.com/opendilab/LMDrive/assets/75245944/0517c317-21dd-4779-a13f-51c7dff380da)
![image](https://github.com/opendilab/LMDrive/assets/75245944/23a8c9c9-b073-43ad-a0a9-7bd98bf7e22f)
In the running process encountered this error, I will remove your comments after the model can run.
![image](https://github.com/opendilab/LMDrive/assets/75245944/563e83c8-2bb9-4189-a795-c4575857a4d4)
![image](https://github.com/opendilab/LMDrive/assets/75245944/8c2afb12-230c-48e5-9659-d95122acd5ce)
However, the model is not able to load the pygame running column during evaluation.
![image](https://github.com/opendilab/LMDrive/assets/75245944/f3c4ee3a-5ae6-4296-a09c-eef85e39d5e3)
![image](https://github.com/opendilab/LMDrive/assets/75245944/31ab3f88-ae15-4c9a-ad40-f80551da7f3e)
Please help me to see if I have made a mistake. Thanks again.

**Comment by zhouxiqin2017** [comment]
> @deepcs233 Hello, I'm sorry to bother you again, but I still have some questions about the model evaluation.您好，很抱歉再次打扰您，我还有一些关于模型评估的问题。 This is my model configuration parameters page.这是我的模型配置参数页面。 ![image](https://private-user-images.githubusercontent.com/75245944/296914324-0517c317-21dd-4779-a13f-51c7dff380da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNTI5MzgsIm5iZiI6MTcwNjI1MjYzOCwicGF0aCI6Ii83NTI0NTk0NC8yOTY5MTQzMjQtMDUxN2MzMTctMjFkZC00Nzc5LWExM2YtNTFjN2RmZjM4MGRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA3MDM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiOWQ1YWQ5YjQ2MGFhYjc1Nzg3ZjE4MzEzNzM2YjY3NTA3NDI4ZTI0NDJiYzM1ZTRiOGVjNDgzMTNhNWYwMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mXv8I59Avbwshc1zbElGHIo_0vDwq-L0bBTwuu-gOVM) ![image](https://private-user-images.githubusercontent.com/75245944/296914905-23a8c9c9-b073-43ad-a0a9-7bd98bf7e22f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNTI5MzgsIm5iZiI6MTcwNjI1MjYzOCwicGF0aCI6Ii83NTI0NTk0NC8yOTY5MTQ5MDUtMjNhOGM5YzktYjA3My00M2FkLWEwYTktN2JkOThiZjdlMjJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA3MDM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmOTVjODQxNzU5ZjRhMmY2YjE2MTM0MzE0ZTg4YTRjNTJiNjRjMWEwYzgwZDZkMTUwOWE0MTRjZDEwNDYyNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S5YjUdv4sKF5HMDwIgL_DXRKfavEMaz311XgEkmv7gI) In the running process encountered this error, I will remove your comments after the model can run.在运行过程中遇到这个错误，我会在模型运行后删除你的评论。 ![image](https://private-user-images.githubusercontent.com/75245944/296915228-563e83c8-2bb9-4189-a795-c4575857a4d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNTI5MzgsIm5iZiI6MTcwNjI1MjYzOCwicGF0aCI6Ii83NTI0NTk0NC8yOTY5MTUyMjgtNTYzZTgzYzgtMmJiOS00MTg5LWE3OTUtYzQ1NzU4NTdhNGQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA3MDM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1OWRjOWU1MGY5MDRjMGEyMDA2M2I5MjQ2ZmRjNjk3NDJhNWNjYTMwNWRlOWVmNzYxMzNjOTgzNjM5NTgzNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TD8jrOVrcV5Q3VfKPzo3Vu58ChVg7UyEJvgMXhw4wOg) ![image](https://private-user-images.githubusercontent.com/75245944/296915264-8c2afb12-230c-48e5-9659-d95122acd5ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNTI5MzgsIm5iZiI6MTcwNjI1MjYzOCwicGF0aCI6Ii83NTI0NTk0NC8yOTY5MTUyNjQtOGMyYWZiMTItMjMwYy00OGU1LTk2NTktZDk1MTIyYWNkNWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA3MDM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhZGJkM2JkZjg4YjAzZmI4NDRlODVhZWVhNmZkZTNjOGQ1YjUzM2YxNGE4ZmRlY2RmMWY0OTEzMmU2MDYwNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JCiGlfNA1zJ-GLe8cKLsw6PUNjnTu6bkHUzlL3zvnFk) However, the model is not able to load the pygame running column during evaluation.但是，该模型在评估期间无法加载 pygame 运行列。 ![image](https://private-user-images.githubusercontent.com/75245944/296915461-f3c4ee3a-5ae6-4296-a09c-eef85e39d5e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNTI5MzgsIm5iZiI6MTcwNjI1MjYzOCwicGF0aCI6Ii83NTI0NTk0NC8yOTY5MTU0NjEtZjNjNGVlM2EtNWFlNi00Mjk2LWEwOWMtZWVmODVlMzlkNWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA3MDM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmYzk5YTEwMGRmNmIyZDliODQwZjlmYmIyMjU1ZGRjNzlmNGNjYTQwYjRjMDlkMTc1ZTMxZTkzY2M2MTM4ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tIcyYuhFFWhtS5XExeeVLBU9o7VTAs99xmcjYuwZzBs) ![image](https://private-user-images.githubusercontent.com/75245944/296915476-31ab3f88-ae15-4c9a-ad40-f80551da7f3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNTI5MzgsIm5iZiI6MTcwNjI1MjYzOCwicGF0aCI6Ii83NTI0NTk0NC8yOTY5MTU0NzYtMzFhYjNmODgtYWUxNS00YzlhLWFkNDAtZjgwNTUxZGE3ZjNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA3MDM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyMDc1NGNlOWFlMGIyYTQ2NmYxNDVjZDZkODNkYmJhNDM0ZDcxZWRmMzNiYTgzNmY2YTRkMWVhZTQzOWI1N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dGmuqiWWNA1j-2trG1-BFgRGLTDD7aswCLSUpdEWCsc) Please help me to see if I have made a mistake. Thanks again.请帮我看看我是否犯了错误。再次感谢。

@deepcs233 Dr. Shao, please look at this problem again

**Comment by deepcs233** [comment]
Hi!

> However, the model is not able to load the pygame running column during evaluation.

Can you show the related error log? Or you can try to comment the GUI codes to evaluate it.

**Comment by zhouxiqin2017** [comment]
[lmdrive_result.json](https://github.com/opendilab/LMDrive/files/14340224/lmdrive_result.json)
Hello, this is the log I run, please help to check.
![image](https://github.com/opendilab/LMDrive/assets/75245944/7c9d15de-5e8e-4d3a-9445-cb2e6222a8b6)

**Comment by deepcs233** [comment]
Hi!

I can't find the detailed reason that caused the error. Maybe you can show the output in your terminal?

**Comment by zhouxiqin2017** [comment]
Thank you. It's settled
