### ISSUE TITLE
BEV Map Visualization

### ISSUE THREAD

**Issue by ry4nzhu** [opendilab/LMDrive#22]
Hi, 
In #21 you give some pointers to the BEV map coordinate, I'm wondering how we can visualize the BEV map processing results made by the vision encoder (like Fig 5 in the paper). Can you give me some brief instructions on how to do that (or pointers)?

Thanks!

**Comment by deepcs233** [comment]
Hi!
You can refer to this script: https://github.com/opendilab/InterFuser/blob/main/interfuser/render.py
The usage of the rendering function: https://github.com/opendilab/InterFuser/blob/4145d6ca58c19ce2a29d319c47980cea05586b06/leaderboard/team_code/interfuser_agent.py#L500

The expected visualization should be like: 
<img width="49" alt="image" src="https://github.com/opendilab/LMDrive/assets/17512647/60e62f86-1bc1-4606-96ce-c29a2af93647">
