### ISSUE TITLE
Where is generate_yamls.py?

### ISSUE THREAD

**Issue by hutchinsonian** [opendilab/LMDrive#28]
I want to reproduce your process of generating data, but according to your tutorial
```
cd dataset
python init_dir.py
cd ..
cd data_collection
python generate_yamls.py # You can modify FPS, waypoints distribution strength ...

# If you do not use 4 servers, the following Python scripts are needed to modify
python generate_bashs.py
python generate_batch_collect.py 
cd ..
```
I did not find the generate_yamls.py file and the script mentioned below, can you give me more information about them and release them?

**Comment by hutchinsonian** [comment]
@deepcs233

**Comment by hutchinsonian** [comment]
I find these in the repo of [Interfuser](https://github.com/opendilab/InterFuser/tree/main/data_collection) according the author's suggestion.

**Comment by zhanghui75** [comment]
Hi, hutchinsonian, have you successfully reproduced the data generation process?

**Comment by deepcs233** [comment]
@hutchinsonian @zhanghui75  Hi, I have updated the Readme. The Lmdrive didn't need to run `python generate_yamls.py`. Sorry for the late reply.
