### ISSUE TITLE
About the LLM model

### ISSUE THREAD

**Issue by dszpr** [opendilab/LMDrive#3]
Hi! Much appreciated for the excellent work!
I noticed that 'the checkpoint path of the llm (LLaMA/Vicuna/LLaVA)' is required for evaluation. I wonder do I need to install LLAVA following their github projects, or just downloading LLAVA checkpoints is adequate to run the evaluation of LMDrive?

**Comment by deepcs233** [comment]
Hi!
Only downloading the  LLAVA checkpoint is OK.
