### ISSUE TITLE
evaluation卡住

### ISSUE THREAD

**Issue by zhangzaibin** [opendilab/LMDrive#34]
您好，非常感谢你的工作和开源。我在运行evaluation代码的时候程序直接结束在下面的状态，请问是为什么。
![image](https://github.com/opendilab/LMDrive/assets/59305487/bca781ad-680e-41d4-81d1-08bf60b9f3b8)

**Comment by deepcs233** [comment]
Hi!
You need to delete the results/sample_result.json. Because the generation code will resume the last collection, or you can set the flag of RESUME as False.
