### ISSUE TITLE
Use simulator and PythonAPI with different versions, Segmentation fault occurs

### ISSUE THREAD

**Issue by dingli-dean** [opendilab/LMDrive#36]
In https://github.com/opendilab/LMDrive/issues/14#issuecomment-1898154122, the author change the PythonAPI version into 0.9.12 and it works fine.
However, when I use simulator and PythonAPI with different versions, Segmentation fault occurs.
Does anyone face the same situation?

The port is openning for sure.

> Python 3.8.18 | packaged by conda-forge | (default, Dec 23 2023, 17:21:28)
Type 'copyright', 'credits' or 'license' for more information
IPython 8.12.3 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import carla
In [2]: client = carla.Client('localhost', 6008)
In [3]: traffic_manager = client.get_trafficmanager(6009)
WARNING: Version mismatch detected: You are trying to connect to a simulator that might be incompatible with this API
WARNING: Client API version     = 0.9.12
WARNING: Simulator API version  = 784d9b9f
Segmentation fault

_Originally posted by @dingli-dean in https://github.com/opendilab/LMDrive/issues/14#issuecomment-2012423471_

**Comment by deepcs233** [comment]
Hi!
What is the version of your Carla simulator and Python API? Can you try to use another traffic manager port, like 6558. 6008+1 is a default streaming port for Carla (https://carla.readthedocs.io/en/latest/start_quickstart/).

**Comment by dong-zeyu** [comment]
Hi @dingli-dean, I had a similar problem when running CARLA. Would you like to provide the compiled CARLA egg for Python 3.8. I appreciate your help!

**Comment by IranQin** [comment]
> Hi @dingli-dean, I had a similar problem when running CARLA. Would you like to provide the compiled CARLA egg for Python 3.8. I appreciate your help!

Do you solve the problem? I have the same problem.
