### ISSUE TITLE
Evaluation speed is too slow

### ISSUE THREAD

**Issue by dingli-dean** [opendilab/LMDrive#38]
Hi, team, thanks for your attention. 
I try to evaluate the released model _LMDrive-llava-v1.5-7b-v1.0_, and observe that the evaluation process is too slow.
Here is the statistics of evaluation in one route scenario, is the evaluation speed as fast as expected ?
Evaluation running on one 3090 GPU.

> ========= Results of RouteScenario_51 (repetition 0) ------ SUCCESS =========
> 
> ╒═════════════════════════════════╤═════════════════════╕
> │ Start Time                      │ 2024-03-26 12:46:58 │
> ├─────────────────────────────────┼─────────────────────┤
> │ End Time                        │ 2024-03-26 13:58:15 │
> ├─────────────────────────────────┼─────────────────────┤
> │ Duration (System Time)          │ 4276.92s            │
> ├─────────────────────────────────┼─────────────────────┤
> │ Duration (Game Time)            │ 324.25s             │
> ├─────────────────────────────────┼─────────────────────┤
> │ Ratio (System Time / Game Time) │ 0.076               │
> ╘═════════════════════════════════╧═════════════════════╛
> 
> ╒═══════════════════════╤═════════╤═════════╕
> │ Criterion             │ Result  │ Value   │
> ├───────────────────────┼─────────┼─────────┤
> │ RouteCompletionTest   │ SUCCESS │ 100 %   │
> ├───────────────────────┼─────────┼─────────┤
> │ OutsideRouteLanesTest │ SUCCESS │ 0 %     │
> ├───────────────────────┼─────────┼─────────┤
> │ CollisionTest         │ SUCCESS │ 0 times │
> ├───────────────────────┼─────────┼─────────┤
> │ RunningRedLightTest   │ SUCCESS │ 0 times │
> ├───────────────────────┼─────────┼─────────┤
> │ RunningStopTest       │ SUCCESS │ 0 times │
> ├───────────────────────┼─────────┼─────────┤
> │ InRouteTest           │ SUCCESS │         │
> ├───────────────────────┼─────────┼─────────┤
> │ AgentBlockedTest      │ SUCCESS │         │
> ├───────────────────────┼─────────┼─────────┤
> │ Timeout               │ SUCCESS │         │
> ╘═══════════════════════╧═════════╧═════════╛

**Comment by aashrith-deepgrid** [comment]
how did u fix this issue?

**Comment by Cynthia11281128** [comment]
Same... Did you fix this?

**Comment by dingli-dean** [comment]
Multi-threading test

**Comment by deepcs233** [comment]
I think it's not an issue, as the Carla simulator runs quite slowly, particularly when the agent is equipped with multiple sensors.
