### ISSUE TITLE
Missing the file "dataset_index_test.txt" 

### ISSUE THREAD

**Issue by TreezzZ** [opendilab/LMDrive#4]
https://github.com/opendilab/LMDrive/blob/684e92241b9969eed9c3c85c9c20fd8842d426dd/vision_encoder/timm/data/carla_dataset.py#L179C62-L179C80

Thanks for your work!

I'm trying to follow your instructions to fine-tune the vision encoder. However, the code shown above needs a file named "dataset_index_test.txt." According to https://huggingface.co/datasets/deepcs233/LMDrive, there is only a file named "dataset_index.txt." I also renamed the file to match your code. But it faced lots of FileNotFoundError when running, indicating these two files do not match. Any idea about this?

**Comment by deepcs233** [comment]
Hi!
It’s ok to rename the file to dataset_index.txt and I will fix it.  But you
also need to download all files in the hugging face, which may solve the
FileNotFoundError.

Tree ***@***.***>于2023年12月23日 周六14:19写道：

**Comment by TreezzZ** [comment]
@deepcs233 Thanks for your reply.

I downloaded all the files, but there are still some missing files. So I write a script to filter out them. There are 14181 tar.gz files in total and 820 files are missing. The attachment is the missing files.
[missing.txt](https://github.com/opendilab/LMDrive/files/13759531/missing.txt)

**Comment by deepcs233** [comment]
Thanks for your feedback! I will check it and update the data.

Tree ***@***.***>于2023年12月23日 周六23:48写道：

**Comment by deepcs233** [comment]
@TreezzZ Hi! We have updated the dataset!
