### ISSUE TITLE
rgb_full camera image resolution mismatch

### ISSUE THREAD

**Issue by qiwang067** [opendilab/LMDrive#43]
Instead of $400 \times 1200$ resolution, the actual `rgb_full` camera image resolution is $800 \times 2400$.

**Comment by deepcs233** [comment]
Hi!
We merge the front, left, right, and rear rgb views into a single image to reduce IO requests. Each view has a size of 800 x 600.

**Comment by qiwang067** [comment]
> Hi! We merge the front, left, right, and rear rgb views into a single image to reduce IO requests. Each view has a size of 800 x 600.

Hi Shao! Thanks for your response.
