### ISSUE TITLE
LlamaFlashAttention2 `__init__` is undefined.

### ISSUE THREAD

**Issue by Luke20000429** [opendilab/LMDrive#60]
The `LlamaFlashAttention2` has no `__init__()`. As a result running the system with flash-attn will crash.
https://github.com/opendilab/LMDrive/blob/ae0643d071b08b38cd326314bcbfb44aa4e60232/LAVIS/lavis/models/blip2_models/modeling_llama.py#L415

**Comment by deepcs233** [comment]
Hi!

Sorry for the late reply. I've been very busy lately.

It's an experimental feature, and you can simply replace the forward function and other related functions from LlamaAttention with those from LlamaFlashAttention2. I also update the code.

**Comment by Luke20000429** [comment]
I've included that in my local repo, but not a bad thing for you to include in your public repo.
