### ISSUE TITLE
如何测试自己采集的数据

### ISSUE THREAD

**Issue by leftdoor** [opendilab/LMDrive#68]
首先感谢您开源的工作！
对模型推理这里还有些不太清楚的地方，想请教一下如何测试自己采集的数据，四个相机的数据+激光点云的数据，需要怎样的预处理过程才能变成跟训练数据一样的层级目录呢？

**Comment by deepcs233** [comment]
你好，运行我们readme提供的数据采集代码，便可以获得route_dir->rgb/lidar 这样的层级目录。至于分town摆放，这是经过后期手工整理的。

**Comment by leftdoor** [comment]
> 你好，运行我们readme提供的数据采集代码，便可以获得route_dir->rgb/lidar 这样的层级目录。至于分town摆放，这是经过后期手工整理的。

看readme介绍好像是对CARLA获取的数据采取的处理方式，如果我想在真实数据（仅有四个相机的MP4数据及激光点云的数据）测试效果，需要怎么处理这些数据来测试呢

**Comment by CoderXuans** [comment]
@leftdoor 
Do you know how to handle real-world data?
