### ISSUE TITLE
llm_model

### ISSUE THREAD

**Issue by CoderXuans** [opendilab/LMDrive#74]
@deepcs233 
Here's the translation:

---

Hello, thank you for open-sourcing such a complex project. What should `llm_model` be set to?

Could not set up the required agent:
> Can't load tokenizer for 'OpenDILabCommunity/LMDrive-vicuna-v1.5-7b-v1.0'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'OpenDILabCommunity/LMDrive-vicuna-v1.5-7b-v1.0' is the correct path to a directory containing all relevant files for a LlamaTokenizer tokenizer.

Could not set up the required agent:
> Can't load tokenizer for 'vicuna'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'OpenDILabCommunity/LMDrive-vicuna-v1.5-7b-v1.0' is the correct path to a directory containing all relevant files for a LlamaTokenizer tokenizer.

Could not set up the required agent:
> Can't load tokenizer for 'LMDrive-vicuna-v1.5-7b-v1.0'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'OpenDILabCommunity/LMDrive-vicuna-v1.5-7b-v1.0' is the correct path to a directory containing all relevant files for a LlamaTokenizer tokenizer.

I have tried these three options and encountered errors. I also tried downloading it locally and specifying the absolute path to the `.pth` file, but encountered issues as well.

---

**Comment by dq0803** [comment]
@CoderXuans Hi, I meet the same problem, did you solve it?

**Comment by CoderXuans** [comment]
As long as the model path is correctly specified in lmdrive_config, no errors will occur.
