### ISSUE TITLE
affordances

### ISSUE THREAD

**Issue by CoderXuans** [opendilab/LMDrive#77]
@deepcs233 
Hello, could you explain what affordances actually are?

**Comment by deepcs233** [comment]
Hi!
Can you provide more details about your question? The affordances used in the pre-training stage are described in our paper, and we do not involve RL in the project.

**Comment by CoderXuans** [comment]
@deepcs233 
I saw this in the dataset section:  
affordances: different types of affordances.  
I don’t quite understand what role this plays.

**Comment by deepcs233** [comment]
Do you mean the "affordances" shown on the GitHub page? We do not use it in our project now. It consists of the status of the traffic light and stop sign. Here is an example:
array({'traffic_light': None, 'stop_sign': False}, dtype=object)
