### ISSUE TITLE
LowLevelFatalError

### ISSUE THREAD

**Issue by CoderXuans** [opendilab/LMDrive#78]
I installed Carla from source, and when I run the command Carla/CarlaUE4.sh --world-port=2000 -opengl, I get the following error:
chmod: Changing permissions of '/home/syl/LMDrive/Carla/Unreal/CarlaUE4/Binaries/Linux/CarlaUE4-Linux-Shipping': Operation not permitted
4.24.3-0+++UE4+Release-4.24 518 0
Disabling core dumps.
LowLevelFatalError [File:Unknown] [Line: 153] 
ICU data directory was not discovered:
../../../CarlaUE4/Content/Internationalization
../../../Engine/Content/Internationalization
Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554 
CommonUnixCrashHandler: Signal=11
Malloc Size=65535 LargeMemoryPoolOffset=131119 
Malloc Size=39760 LargeMemoryPoolOffset=170896 
Malloc Size=65538 LargeMemoryPoolOffset=236450 
LowLevelFatalError [File:Unknown] [Line: 508] 
Error copying clipboard contents: Video subsystem must be initialized to set clipboard text

Malloc Size=131160 LargeMemoryPoolOffset=367640 
Malloc Size=131160 LargeMemoryPoolOffset=498824 
Malloc Size=131160 LargeMemoryPoolOffset=630008 
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
Segmentation fault (core dumped)
I compiled Carla from source to change the road material. Has anyone encountered this issue?

**Comment by deepcs233** [comment]
Hi！
Maybe you need to refer to Carla's Github Repo. I recommend you to change the graphics card. It looks like the GPU memory is not enough.
