### ISSUE TITLE
Remove the suddenly appearing pedestrians

### ISSUE THREAD

**Issue by CoderXuans** [opendilab/LMDrive#81]
@deepcs233 
Hello, how can I remove the suddenly appearing pedestrians? In which folder should I modify to achieve this？

**Comment by deepcs233** [comment]
Hi!
You can try this scenario file: https://github.com/opendilab/LMDrive/blob/43fc2e9a914623fd6eec954a94aeca2d3966e3db/leaderboard/scripts/run_evaluation.sh#L26

It will remove all the sudden scenarios, including the suddenly appearing pedestrians.

**Comment by CoderXuans** [comment]
Does town05_all_scenarios.json contain anything else besides suddenly appearing pedestrians?

**Comment by deepcs233** [comment]
No,  I mean using this code:

```bash
export SCENARIOS=leaderboard/data/scenarios/no_scenarios.json
```

**Comment by CoderXuans** [comment]
Thank you for your quick response.
1、I understand what you mean. What I’m asking is whether the contents of town05_all_scenarios.json are solely for serving suddenly appearing pedestrians?
2、How can I modify other vehicles on the road? For example, how can I delete the other vehicles?

**Comment by deepcs233** [comment]
1. town05_all_scenarios.json includes many types of scenarios that appear in Town05. BTW, you can check the `scenario_type` in the scenarios.json, and the mapping from the type id to the scenario class can be found here: https://github.com/opendilab/LMDrive/blob/43fc2e9a914623fd6eec954a94aeca2d3966e3db/scenario_runner/srunner/scenarios/route_scenario.py#L53 .  You could remove the scenarios of a specified type.
2. I'm not familiar with this question. Maybe this class can help you: https://github.com/opendilab/LMDrive/blob/43fc2e9a914623fd6eec954a94aeca2d3966e3db/leaderboard/leaderboard/scenarios/background_activity.py#L20

https://github.com/carla-simulator/leaderboard and https://github.com/carla-simulator/scenario_runner can help you resolve this kind of questions.

**Comment by CoderXuans** [comment]
May I ask where I can modify the responses for the four types: Follow, Turn, Others, and Notice?
