### ISSUE TITLE
视觉编码器的结构选择

### ISSUE THREAD

**Issue by CoderXuans** [opendilab/LMDrive#84]
@deepcs233 
请问选择memfuser_baseline_return_feature或memfuser_baseline_e1d3_return_feature的依据是什么呢？这两个效果差不多吗？

**Comment by deepcs233** [comment]
你好，效果差不多，但是e1d3模型更小，推理速度更快

**Comment by CoderXuans** [comment]
谢谢你的回复，现在我明白了
