### ISSUE TITLE
更改指令的描述

### ISSUE THREAD

**Issue by CoderXuans** [opendilab/LMDrive#96]
@deepcs233 
你好，在您的项目中有一个专门存指令的文件instruction_dict.json，我如果想要修改评估时显示在屏幕上可选择的输出，修改instruction_dict.json中的描述可以实现吗？比如原来的{"0": ["Proceed ahead and make a left turn.", "Just up ahead, take a left.", "Left ahead.", "Hang a left up front.", "Prepare to turn left up ahead.", "Your next action is a left turn, just ahead.", "Up ahead, just take a left.", "A left turn is required up ahead."], 
更改为{"0": ["Move forward and take a left turn.", "Ahead of you, turn left.", "Turn left up ahead.", "Turn left aheadt.", "Get ready to turn left soon.", "The next move is a left turn, coming up ahead.", "Just ahead, make a left turn.", "A left turn is needed ahead."]
更改后的数据会在评估时显示在屏幕上吗？

**Comment by deepcs233** [comment]
可以的

**Comment by CoderXuans** [comment]
谢谢你的回复，更改有什么需要注意的吗？比如说原来是左转，如果我改成意思不一致的右转，仿真中的车辆会左转，但是屏幕的输出是右转，这样可以做到吗？

**Comment by deepcs233** [comment]
可以修改为类似含义的语句。最好不要改成其他意思，这样改会导致不可预知的错误。

**Comment by CoderXuans** [comment]
好的，谢谢你
