### ISSUE TITLE
Could you please provide the detailed requirement.txt of your environment?

### ISSUE THREAD

**Issue by Jonathans575** [opendilab/LMDrive#97]
I don't know the version of packages, which gave me a lot of trouble when setting up the environment.

**Comment by deepcs233** [comment]
Hi!

Could you follow the Setup section in the Readme? We also list the related package info here:

https://github.com/opendilab/LMDrive/blob/main/environment.yml
https://github.com/opendilab/LMDrive/blob/main/LAVIS/requirements.txt
https://github.com/opendilab/LMDrive/blob/main/vision_encoder/requirements.txt

**Comment by Jonathans575** [comment]
Thanks.
This file is useful to solve my problem : https://github.com/opendilab/LMDrive/blob/main/environment.yml
